
const fs = require('fs');
const path = require('path');

const galleryPath = "d:/personal project/the-green-martyrdom---sharif-osman-hadi/components/Gallery.tsx";
const outputPath = "d:/personal project/the-green-martyrdom---sharif-osman-hadi/config/secureMedia.ts";

console.log('Starting simplified script...');
console.log('Reading:', galleryPath);

try {
    if (!fs.existsSync(galleryPath)) {
        console.error('ERROR: Gallery file missing!');
        process.exit(1);
    }

    const content = fs.readFileSync(galleryPath, 'utf8');
    const videoMatch = content.match(/const rawVideoUrls = \[([\s\S]*?)\];/);
    const photoMatch = content.match(/const rawPhotoUrls = \[([\s\S]*?)\];/);

    if (!videoMatch || !photoMatch) {
        console.error('ERROR: Regex match failed.');
        process.exit(1);
    }

    const extractUrls = (rawString) => {
        return rawString.split(',')
            .map(line => {
                const match = line.match(/['"](.*?)['"]/);
                return match ? match[1] : null;
            })
            .filter(url => url !== null);
    };

    const videoUrls = extractUrls(videoMatch[1]);
    const photoUrls = extractUrls(photoMatch[1]);
    console.log(`Extracted: ${videoUrls.length} videos, ${photoUrls.length} photos`);

    const encrypt = (url) => Buffer.from(url).toString('base64');

    const fileContent = `// Security Layer: Media Link Obfuscation
// Do not edit this file directly. Generated by script.

export const d = (str: string): string => {
    // Browser environment
    if (typeof window !== 'undefined') {
        return atob(str);
    }
    // Node environment (optional fallback)
    return Buffer.from(str, 'base64').toString('utf-8');
};

export const encryptedVideoArgs = [
${videoUrls.map(url => `    "${encrypt(url)}"`).join(',\n')}
];

export const encryptedPhotoArgs = [
${photoUrls.map(url => `    "${encrypt(url)}"`).join(',\n')}
];
`;

    const configDir = path.dirname(outputPath);
    if (!fs.existsSync(configDir)) {
        fs.mkdirSync(configDir, { recursive: true });
    }

    fs.writeFileSync(outputPath, fileContent);
    console.log('SUCCESS: secureMedia.ts written.');

} catch (e) {
    console.error('EXCEPTION:', e);
    process.exit(1);
}
